on:
  push:
    branches: [ main ]

jobs:
  build: 
     runs-on: ubuntu-latest

     steps:
       - name: checkout code
         uses: actions/checkout@53

       - name: setup node
         uses: actions/setup-node@v3
         with:
            node-version: 18

       - name: install dependencies
         run: npm install

       - name: Run test.js
         run: npm test